// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA1N5fo_Rg2wQnIVccfkOIPoZ6JsddiGI',
    appId: '1:1079032667699:web:0b851e35be77ae9d9b0d46',
    messagingSenderId: '1079032667699',
    projectId: 'rsls-952dd',
    authDomain: 'rsls-952dd.firebaseapp.com',
    storageBucket: 'rsls-952dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA1N5fo_Rg2wQnIVccfkOIPoZ6JsddiGI',
    appId: '1:1079032667699:android:4b1ecd6a83025fc79b0d46',
    messagingSenderId: '1079032667699',
    projectId: 'rsls-952dd',
    storageBucket: 'rsls-952dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'remote-sampling-lab',
    storageBucket: 'remote-sampling-lab.appspot.com',
    iosBundleId: 'com.example.remoteSamplingLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'remote-sampling-lab',
    storageBucket: 'remote-sampling-lab.appspot.com',
    iosBundleId: 'com.example.remoteSamplingLab',
  );
}